#include "+A.h"




void +A::+perimetre()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 127-0-0-1-56b95e1e:16dee880cf0:-8000:0000000000000909 begin
{
}
// section 127-0-0-1-56b95e1e:16dee880cf0:-8000:0000000000000909 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void +A::+size()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 127-0-0-1-56b95e1e:16dee880cf0:-8000:000000000000090B begin
{
}
// section 127-0-0-1-56b95e1e:16dee880cf0:-8000:000000000000090B end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
